customer: CUSTOMER_NAME
default: CME
exchange:
 CME:
  symbols: ZC,OZC,ZW,OZW,ZM,OZM
  ip: 172.23.25.149 
  inteface: eth1
  type:
  account:

 CBOE:
  symbols:
  ip:
  interface:
  account:

 ICE:
  symbols:
  ip:
  interface:
  account:

 AMEX:
  symbols:
  ip:
  interface:
  account:

 ACTIV:
  symbols:
  ip:
  interface:
  account:

 CFE:
  symbols:
  ip: 
  interface:
  account:
  

users: 
  BATMAN: wayne 
  SUPERMAN: kent
  FLASH: west
