customer: CONSOLIDATED_ICE 
default: CME
exchange:
 CME:
  symbols: ES 
  ip: 10.191.74.8 
  interface: eth2

 ICE:
  symbols:
  sendercompid: 
  sendersubid: 
  username:
  traderid:
  clearingaccount:
  clearingfirmid:

 CBOE:
  cas:
  interface:
  user:
  password:
  orderbranch:
  giveupfirm:
  orderaccount:
  ordersubaccount:
  supportedroductclasses: 
  

users: 
  CHRIS: moag
  JEFF: melgarde
