customer: CHONG_BACKUP 
default: CME
exchange:
 CME:
  symbols: ES,ZC,ZS,ZW,CL,LO,OZC,OZS,OZW
  ip: 10.191.74.4 
  interface: eth0

 ICE:
  symbols: CT,KC,SB
  sendercompid: 2800 
  sendersubid: 114
  username: fcsoptcos-mq
  traderid: fcsoptc-mq1
  clearingaccount: 14700
  clearingfirmid: 3370
  traderusername: TOM
  psusername: fcsoptcps2
  interface: eth2

 CBOE:
  cas:
  interface:
  user:
  password:
  orderbranch:
  giveupfirm:
  orderaccount:
  ordersubaccount:
  supportedroductclasses: 
  

users: 
  TOM: chong
  JOHN: scaife
